apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-faminto
  name: pod-faminto
  namespace: treinamento-ch2
spec:
  containers:
  - image: polinux/stress
    name: stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
