apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-comportado
  name: pod-comportado
  namespace: treinamento-ch2
spec:
  containers:
  - image: polinux/stress
    name: stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
    resources:
      limits:
        memory: "300Mi" #leave a good margin for the pod to run
      requests:
        memory: "250Mi"
