apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-deployment
  name: busybox-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: busybox-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: busybox-deployment
    spec:
      containers:
      - image: busybox:1.36.1
        name: busybox
        command: ["/bin/sh", "-c", "echo 'Testando essa bagaça' > index.html && httpd -f -p 80"] #Inicia um webserver e cria uma pagina
        resources:
          limits:
            cpu: "0.55"
            memory: 256Mi
          requests:
            cpu: 0.33
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - wget
            - -q
            - -O-
            - http://localhost:80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 4
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
